config/routes.rb
Rocketstart::Application.routes.draw do

  root :to => "general#index"

  get "/login" => "session#new"
  match 'logout' => 'session#destroy'

  resource :session, :controller => :session, :only => [:create, :destroy]
  resource :remined, :only => [:new, :create, :edit, :update], :controller => 'users/remined'
  resource :entry, :controller => :entry do
    collection { get(:complete) }
  end

  #userに関する関する責務
  resources :users
  namespace :users do
    resource :entry, :controller => :entry, :only => [:new, :create] do
      collection { get(:complete) }
    end

    resource :email, :controller => :email, :only => [:new, :create] do
      collection do 
        get :complete
        get :send_complete
      end
    end
    match "/register/emailchange/:code" => "email#update", :as => "email_change", :via => :put
    match "/register/emailchange/:code" => "email#edit", :as => "email_change"

    #namespace :entry do
    #  resources :search, :only => [:index, :create]
    #end
    resource :register, :only => [:new, :create, :update], :controller => 'register'
    match "/register/remined/:token" => "register#remined", :as => :register_remined_with_token
    match "/register/new/:code" => "register#new", :as => "register_with_token"

    resources :invitation, :only => [:new, :create]
    namespace :invitation do
      resource :register, :only => [:new, :create], :controller => "register" do
        collection { get(:complete) }
      end
      match "register/new/:code" => "register#new", :as => :register_invitation_with_token
    end

  end

  resource :dashboard, :controller => :dashboard, :only => [:show]

end

app/models/user.rb
class User < ActiveRecord::Base
  include Authentication
  EditTargets = []
  RollName = ""
  attr_accessor :password, :password_confirmation, :roll

  validates :email, :uniqueness => true, :presence => true
  validates :name, :presence => true
  validates :password, :length => { :minimum => 6 }, :on => :create
  validates :password, :presence => true, :confirmation => true, :on => :create

  before_save :encrypt_password

  has_many :reports
  has_many :drop_boxes

  has_many :users_schedules, :class_name => 'Relations::UsersSchedule'
  has_one :profile, :class_name => '::User::Profile'

  accepts_nested_attributes_for :profile

  belongs_to :company

  class << self
    def authenticate_email(email, password)
      return nil if email.blank? || password.blank?
      u = find_by_email(email)
      u && u.authenticated?(password) ? u : nil
    end
  end

  def roll_change
    return if self.roll.blank?
    #TODO:あとでAbstractFactoryとvalidation
    type_text = 
    case self.roll.to_i
    when 1
      "User::Administrator"
    when 2
      "User::President"
    when 3
      "User::EdicationalOfficer"
    when 4
      "User::SystemOfficer"
    when 5
      "User::Staff"
    when 6
      "User::AuditOfficer"
    else
      raise UserTypeNotFound
    end
    self.class.update_all("type='#{type_text}'", ["id = ?", self.id])
  end

  def president?
    self.class == ::User::President
  end

  def user_type
    actor = self.class.to_s.split("::").last
    C.user_type.send(actor.to_sym)
  end

  def waiting_workflows
    ::ApprovalWorkflow.where(user_type: self.user_type)
  end
end

app/models/user/administrator.rb
#coding: utf-8
class User::Administrator < User
  ROLL = "管理者".freeze
  RollOptions = [[::User::Administrator::ROLL,1],[::User::EdicationalOfficer::ROLL,3],[::User::SystemOfficer::ROLL,4],[::User::Staff::ROLL,5]].freeze
  EditTargets = [::User::EdicationalOfficer, ::User::SystemOfficer, ::User::Staff].freeze
  has_many :reports, :class_name => "ApprovalForm", :foreign_key => :user_id
end

app/models/user/audit_officer.rb
#coding: utf-8
class User::AuditOfficer < User
  ROLL = "監査責任者".freeze
end

app/models/user/edicational_officer.rb
#coding: utf-8
class User::EdicationalOfficer < User
  ROLL = "教育責任者".freeze
end

app/models/user/president.rb
#coding: utf-8
class User::President < User
  ROLL = "社長".freeze
  RollOptions = [[::User::Administrator::ROLL,1],[::User::Staff::ROLL,5],[::User::AuditOfficer::ROLL,6]].freeze
  EditTargets = [::User::Administrator, ::User::Staff, ::User::AuditOfficer].freeze
end

app/models/user/profile.rb
class User::Profile < ActiveRecord::Base
end

app/models/user/staff.rb
#coding: utf-8
class User::Staff < User
  ROLL = "従業員".freeze
end

app/models/user/system_officer.rb
#coding: utf-8
class User::SystemOfficer < User
  ROLL = "情報システム・リスク責任者".freeze
end

app/controllers/users/email_controller.rb
#coding: utf-8
class Users::EmailController < ApplicationController
  before_filter :token_required, :only => [:edit, :update]

  def edit
    @user = @token.user
  end

  def create
    token = EmailChangeToken.new(user_id: current_user.id, email: params[:email])
    User::transaction do
      if token.save
        DeliverMailer.email_change(token).deliver
        redirect_to send_complete_users_email_path and return
      else
        render "users/edit"
      end
    end
  end

  def update
    @user = @token.user
    u = User.authenticate(@user.email, params[:password])
    if u && @user.id == u.id
      User::transaction do
        @user.email = @token.email
        @user.save!
        @token.destroy
        redirect_to complete_users_email_path and return
      end
    else
      flash[:error] = "パスワードが違います"
      render "edit"
    end
  end

  def complete; end

  def send_complete; end

  private
  def token_required
    @token = ::EmailChangeToken.where(["code like ? ", "%#{params[:code]}%"]).first
  end

end

app/controllers/users/entry_controller.rb
class Users::EntryController < ApplicationController
  def new
    if params[:master_id].present?
      if master = ::Master::OfficialCompany.find_by_id(params[:master_id])
        @company = ::Company.new(
          :name => master.name,
          :address => master.address,
          :code => master.code,
          :expiration_date => master.expiration_date,
          :agency => master.agency,
          :jis_code => master.jis_code
        )
      else
        @company = ::Company.new
      end
    else
      @company = ::Company.new
    end
    @admin = ::User::Administrator.new
  end

  def create
    @company, @admin = [ ::Company.new, ::User::Administrator.new ]

    #TODO:ohat あとできれいに
    if master = ::Master::OfficialCompany.find_by_id(params[:master_id])
      @company = ::Company.new(
        :name => master.name,
        :address => master.address,
        :code => master.code,
        :expiration_date => master.expiration_date,
        :agency => master.agency,
        :jis_code => master.jis_code
      )
    end

    @admin.attributes = params[:company][:user_administrator]
    params[:company].delete(:user_administrator)

    @company.attributes = params[:company]

    ::Company::transaction do 
      if @company.valid? && @admin.valid?
        @company.save! and @company.reload
        @admin.company_id = @company.id
        @admin.save!
        @token = ActivationToken.create(email: @admin.email)
        DeliverMailer.entry(@token).deliver
        redirect_to complete_users_entry_path and return 
      else
        render "new"
      end
    end
  end
end

app/controllers/users/invitation/register_controller.rb
class Users::Invitation::RegisterController < ApplicationController
  class InvitationTokenNotFound < StandardError; end
  class UserTypeNotFound < StandardError; end
  before_filter :token_required, :except => [:complete]

  def new
    @user = user_klass(@token).new(email: @token.email)
    @company = @token.user.company
  end

  def create
    @user = user_klass(@token).new(email: @token.email, company_id: @token.company_id)
    @company = @token.user.company
    key = @user.class.to_s.split("::").last.underscore
    @user.attributes = params["user_#{key}".to_s]
    ActiveRecord::Base.transaction do
      if @user.save
        @user.status = C.regist_status.REGISTED
        @token.destroy
        DeliverMailer.registed(@user).deliver
        self.current_user= @user
        redirect_to complete_users_invitation_register_path and return
      else
        render "new"
      end
    end
  end

  private
  def token_required
    @token = ::InvitationToken.where(["code like ? ", "%#{params[:code]}%"]).first
    raise InvitationTokenNotFound unless @token.present?
  end

  #TODO:ohta
  #あとでアブストラクトファクトリー
  def user_klass(token)
    case token.user_type
    when 2
      ::User::President
    when 3
      ::User::EdicationalOfficer
    when 4
      ::User::SystemOfficer
    when 5
      ::User::Staff
    when 6
      ::User::AuditOfficer
    else
      raise UserTypeNotFound
    end
  end
end

app/controllers/users/invitation_controller.rb
#coding: utf-8
class Users::InvitationController < ApplicationController
  def new
    @invitation = ::InvitationToken.new(user_id: current_user.id)
  end

  def create
    @invitation = ::InvitationToken.new(user_id: current_user.id, company_id: current_user.company.id)
    @invitation.attributes = params[:invitation_token]

    ActiveRecord::Base::transaction do
      if @invitation.save
        flash[:notice] = "invitationしました"
        DeliverMailer.invitation(@invitation).deliver
        redirect_to(users_path) and return
      else
        render("new") and return
      end
    end
  end
end

app/controllers/users/register_controller.rb
#coding: utf-8
class Users::RegisterController < ApplicationController
  class TokenNotFound < StandardError; end
  before_filter :token_required

  rescue_from TokenNotFound do
    render :text => "token not found"
  end

  def new
    @user = ::User::find_by_email @token.email
  end

  def create
    @user = ::User::find_by_email @token.email
    u = User.authenticate(@user.email, params[:user][:password])

    if u
      ActiveRecord::Base::transaction do
        self.current_user= u
        @user.status = C.regist_status.REGISTED
        c = @user.company
        c.status = C.regist_status.REGISTED
        c.save!
        @user.save!
        @token.destroy
        DeliverMailer.registed(@user).deliver
        redirect_to dashboard_path and return
      end
    else
      flash[:error] = "パスワードが違います"
      render "new"
    end
  end

  private
  def token_required
    #@token = ActivationToken.find_by_code(params[:code])
    #TODO;sqlite?
    @token = ActivationToken.where([" code like ? ", "%#{params[:code]}%"]).first
    raise TokenNotFound unless @token.present?
  end

end

app/controllers/users/remined_controller.rb
#coding: utf-8
class Users::ReminedController < ApplicationController

  def new
    @entry = ActivationToken.new
    @entry.remined = 1
    render :new
  end

  def create
    @entry = ActivationToken.new
    @entry.attributes = params[:activation_token]
    @entry.save!
    if @entry.remined?
      user = User.find_by_email @entry.email
      if user
        DeliverMailer.remined(@entry).deliver
      else
        #ここにユーザー登録されていない場合の処理を書く
      end
    else
      DeliverMailer.entry(@entry).deliver
    end
    render :complete
  end

  def edit
    @entry = ActivationToken.find_by_token(params[:token])
    if @entry
      @user = User.find_by_email @entry.email
    else
      raise TokenNotFound
    end
  end

  def update
    @user = User.find_by_email params[:user][:email]
    @user.attributes = params[:user]
    @user.save!
    ActivationToken.find_by_email(u.email).destroy
    self.current_user = @user
    redirect_to dashboard_path
  end

end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  def index
    @users = User.where(company_id: current_user.company_id)
  end

  def edit
    @user = current_user.company.users.find params[:id]
  end

  def update
    @user = current_user.company.users.find params[:id]
    key = "user_" + @user.class.to_s.split("::").last.underscore

    User::transaction do
      if @user.update_attributes(params[key])
        @user.roll_change
        redirect_to users_path
      else
        render "edit"
      end
    end
  end

  def destroy
    #TODO:権限周りやその他、ひもづいている者を全て削除する
    u = User.find(params[:id])
    (::Schedule.where :owner_id => u.id).each do |s|
      s.destroy
    end
    (::UsersSchedule.where :user_id => u.id).each do |us|
      us.destroy
    end
    u.destroy
    redirect_to(users_url, :notice => 'ユーザーを削除しました。') 
  end
end

app/helpers/users/entry/search_helper.rb
module Users::Entry::SearchHelper
end

app/helpers/users/entry_helper.rb
module Users::EntryHelper
end

app/helpers/users/invitation/register_helper.rb
module Users::Invitation::RegisterHelper
end

app/helpers/users/invitation_helper.rb
module Users::InvitationHelper
end

app/helpers/users/register_helper.rb
module Users::RegisterHelper
end

app/views/users/entry/complete.html.erb
<section class="complete">
  <h3>仮登録完了</h3>
  <p>ご登録いただいたメールに認証URLを送信いたしました。</p>
    <br>
    <p>メールに記載された手順にそってアカウントを有効にしてください！</p>
</section>

app/views/users/entry/new.html.erb
<script type="text/javascript">
<!--
  $(document).ready(function(){

    //リッチフォームの設定
    fp = new FormPresenter(
      '/assets/check.png',
      {
        company_name: {
          event: "keyup",
          normal_css: [ "background-color: #ffffff" ],
          highlight_css: [ "background-color: #ffcccc" ],
          validations: [
            { type: "not_null", msg: "" }
          ],
          place_holder: {
            msg: "ご担当者名を入力してください。",
            css: [ "color: #333333"]
          }
        },
        company_address: {
          event: "keyup",
          normal_css: [ "background-color: #ffffff" ],
          highlight_css: [ "background-color: #ffcccc" ],
          validations: [
            { type: "not_null", msg: "" }
          ],
          place_holder: {
            msg: "会社の住所を入力してください。",
            css: [ "color: #333333"]
          }
        },
        company_user_administrator_name: {
          event: "keyup",
          normal_css: [ "background-color: #ffffff" ],
          highlight_css: [ "background-color: #ffcccc" ],
          validations: [
            { type: "not_null", msg: "" }
          ],
          place_holder: {
            msg: "お名前を入力してください。",
            css: [ "color: #333333"]
          }
        },
        company_user_administrator_email: {
          event: "keyup",
          normal_css: [ "background-color: #ffffff" ],
          highlight_css: [ "background-color: #ffcccc" ],
          validations: [
            { type: "email_format", msg: "" }
          ],
          place_holder: {
            msg: "メールアドレスを入力してください。",
            css: [ "color: #333333" ]
          }
        },
        company_user_administrator_password: {
          event: "keyup",
          normal_css: [ "background-color: #ffffff" ],
          highlight_css: [ "background-color: #ffcccc" ],
          validations: [
            { type: "not_null", msg: "" }
          ]
        },
        company_user_administrator_password_confirmation: {
          event: "keyup",
          normal_css: [ "background-color: #ffffff" ],
          highlight_css: [ "background-color: #ffcccc" ],
          validations: [
            { type: "not_null", msg: "" }
          ]
        }
        /* 現在FormPresenterは、checkbox,selectbox,raioに対応していない。
        company_user_administrator_sex: {
          event: "click",
          normal_css: [ "background-color: #ffffff" ],
          highlight_css: [ "background-color: #ffcccc" ],
          validations: [
            { type: "checked", msg: "" }
          ]
        }
        company_user_administrator_birthday: {
          event: "keyup",
          normal_css: [ "background-color: #ffffff" ],
          highlight_css: [ "background-color: #ffcccc" ],
          validations: [
            { type: "not_null", msg: "" }
          ]
        }
        */
      }
    ).load().event_watch();
  });

//-->
</script>

<% if @company.errors.present? || @admin.errors.present? %>
  <div id="error_explanation">
    <ul>
      <% @company.errors.full_messages.each do |msg| %>
      <li><span class="red"><%= msg %></span></li>
      <% end %>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><span class="red"><%= msg %></span></li>
       <% end %>
    </ul>
  </div>
<% end %>

<h2>会員登録</h2>
<%= form_for @company, :url => users_entry_path do |f| %>
  <table class="input_base">
    <thead>
      <tr><th colspan="4">会社情報</th></tr>
    </thead>
    <tbody>
      <tr>
        <th>会社名</th>
        <td class="required"><div class="required">必須</div></td>
        <td><%= f.text_field :name, :class => :input_text -%></td>
        <td><div id="notice_company_name"></div></td>
      </tr>
      <tr>
        <th>住所</th>
        <td class="required"><div class="required">必須</div></td>
        <td><%= f.text_field :address, :class => :input_text -%></td>
        <td><div id="notice_company_address"></div></td>
      </tr>
    </tbody>
  </table>
  <br />
  <table class="input_base">
    <thead>
      <tr><th colspan="4">個人情報保護責任者情報</th></tr>
    </thead>
    <tbody>
    <%= f.fields_for @admin, :admin  do |admin|-%>
      <tr>
        <th>名前</th>
        <td class="required"><div class="required">必須</div></td>
        <td><%= admin.text_field :name, :class => :input_text -%></td>
        <td><div id="notice_company_user_administrator_name"></div></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td class="required"><div class="required">必須</div></td>
        <td><%= admin.text_field :email, :class => :input_text -%></td>
        <td><div id="notice_company_user_administrator_email"></div></td>
      </tr>
      <tr>
        <th>パスワード</th>
        <td class="required"><div class="required">必須</div></td>
        <td><%= admin.password_field :password, :class => :input_text -%></td>
        <td><div id="notice_company_user_administrator_password"></div></td>
      </tr>
      <tr>
        <th>パスワード(確認)</th>
        <td class="required"><div class="required">必須</div></td>
        <td><%= admin.password_field :password_confirmation, :class => :input_text -%></td>
        <td><div id="notice_company_user_administrator_password_confirmation"></div></td>
      </tr>
      <%= admin.fields_for :profile_attributes, @admin.build_profile  do |profile| -%>
        <tr>
          <th>部署</th>
          <td class="required"></td>
          <td><%= profile.text_field :section, :class => :input_text -%></td>
          <td></td>
        </tr>
        <tr>
          <th>肩書き</th>
          <td class="required"></td>
          <td><%= profile.text_field :position, :class => :input_text -%></td>
          <td></td>
        </tr>
        <tr>
          <th>性別</th>
          <td class="required"><div class="required">必須</div></td>
          <td>
            <%- [["男","1"],["女", "2"]].each  do |opt| -%>
	      <%= opt.first %>
              <%= profile.radio_button :sex, opt.last, :required => true %>
            <%- end -%>
          </td>
          <td><div id="notice_company_user_administrator_sex"></div></td>
        </tr>
        <tr>
          <th>誕生日</th>
          <td class="required"><div class="required">必須</div></td>
          <td><%= profile.date_select :birthday %></td>
          <td><div id="notice_company_user_administrator_birthday"></div></td>
        </tr>
        <%- end -%>
      </tbody>
    <%- end -%>
  </table>
  <%= hidden_field_tag :master_id, params[:master_id] if params[:master_id].present? %>
  <div id="none_button" style="display : none;">
    <input type="button" value="登録する" disabled />
  </div>
  <div id="send_button" style="display : none;">
    <input type="submit" value="登録する" />
  </div>
<%- end -%>