config/routes.rb
Rocketstart::Application.routes.draw do

  root :to => "general#index"

  get "/login" => "session#new"
  match 'logout' => 'session#destroy'

  resource :session, :controller => :session, :only => [:create, :destroy]
  resource :remined, :only => [:new, :create, :edit, :update], :controller => 'users/remined'
  resource :entry, :controller => :entry do
    collection { get(:complete) }
  end

  #userに関する関する責務
  resources :users
  namespace :users do
    resource :entry, :controller => :entry, :only => [:new, :create] do
      collection { get(:complete) }
    end

    resource :email, :controller => :email, :only => [:new, :create] do
      collection do 
        get :complete
        get :send_complete
      end
    end
    match "/register/emailchange/:code" => "email#update", :as => "email_change", :via => :put
    match "/register/emailchange/:code" => "email#edit", :as => "email_change"

    #namespace :entry do
    #  resources :search, :only => [:index, :create]
    #end
    resource :register, :only => [:new, :create, :update], :controller => 'register'
    match "/register/remined/:token" => "register#remined", :as => :register_remined_with_token
    match "/register/new/:code" => "register#new", :as => "register_with_token"

    resources :invitation, :only => [:new, :create]
    namespace :invitation do
      resource :register, :only => [:new, :create], :controller => "register" do
        collection { get(:complete) }
      end
      match "register/new/:code" => "register#new", :as => :register_invitation_with_token
    end

  end

  resource :dashboard, :controller => :dashboard, :only => [:show]

end

app/controllers/users/invitation/register_controller.rb
class Users::Invitation::RegisterController < ApplicationController
  class InvitationTokenNotFound < StandardError; end
  class UserTypeNotFound < StandardError; end
  before_filter :token_required, :except => [:complete]

  def new
    @user = user_klass(@token).new(email: @token.email)
    @company = @token.user.company
  end

  def create
    @user = user_klass(@token).new(email: @token.email, company_id: @token.company_id)
    @company = @token.user.company
    key = @user.class.to_s.split("::").last.underscore
    @user.attributes = params["user_#{key}".to_s]
    ActiveRecord::Base.transaction do
      if @user.save
        @user.status = C.regist_status.REGISTED
        @token.destroy
        DeliverMailer.registed(@user).deliver
        self.current_user= @user
        redirect_to complete_users_invitation_register_path and return
      else
        render "new"
      end
    end
  end

  private
  def token_required
    @token = ::InvitationToken.where(["code like ? ", "%#{params[:code]}%"]).first
    raise InvitationTokenNotFound unless @token.present?
  end

  #TODO:ohta
  #あとでアブストラクトファクトリー
  def user_klass(token)
    case token.user_type
    when 2
      ::User::President
    when 3
      ::User::EdicationalOfficer
    when 4
      ::User::SystemOfficer
    when 5
      ::User::Staff
    when 6
      ::User::AuditOfficer
    else
      raise UserTypeNotFound
    end
  end
end

app/controllers/users/invitation_controller.rb
#coding: utf-8
class Users::InvitationController < ApplicationController
  def new
    @invitation = ::InvitationToken.new(user_id: current_user.id)
  end

  def create
    @invitation = ::InvitationToken.new(user_id: current_user.id, company_id: current_user.company.id)
    @invitation.attributes = params[:invitation_token]

    ActiveRecord::Base::transaction do
      if @invitation.save
        flash[:notice] = "invitationしました"
        DeliverMailer.invitation(@invitation).deliver
        redirect_to(users_path) and return
      else
        render("new") and return
      end
    end
  end
end

app/controllers/users/register_controller.rb
#coding: utf-8
class Users::RegisterController < ApplicationController
  class TokenNotFound < StandardError; end
  before_filter :token_required

  rescue_from TokenNotFound do
    render :text => "token not found"
  end

  def new
    @user = ::User::find_by_email @token.email
  end

  def create
    @user = ::User::find_by_email @token.email
    u = User.authenticate(@user.email, params[:user][:password])

    if u
      ActiveRecord::Base::transaction do
        self.current_user= u
        @user.status = C.regist_status.REGISTED
        c = @user.company
        c.status = C.regist_status.REGISTED
        c.save!
        @user.save!
        @token.destroy
        DeliverMailer.registed(@user).deliver
        redirect_to dashboard_path and return
      end
    else
      flash[:error] = "パスワードが違います"
      render "new"
    end
  end

  private
  def token_required
    #@token = ActivationToken.find_by_code(params[:code])
    #TODO;sqlite?
    @token = ActivationToken.where([" code like ? ", "%#{params[:code]}%"]).first
    raise TokenNotFound unless @token.present?
  end

end

app/helpers/users/invitation/register_helper.rb
module Users::Invitation::RegisterHelper
end

app/helpers/users/invitation_helper.rb
module Users::InvitationHelper
end

app/helpers/users/register_helper.rb
module Users::RegisterHelper
end

app/views/users/invitation/register/complete.html.erb
<div id="main">
<h3>登録が完了しました</h3>
<p><%= link_to "ホームへ", dashboard_path %></p>
</div>

app/views/users/invitation/register/new.html.erb
<div id="entry">
  <br />
  <!-- #TODO:yokohama バリデーションの実装 -->
<% if @user.errors.present? %>
<div id="error_explanation">
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><span class="red"><%= msg %></span></li>
    <% end %>
  </ul>
</div>
<% end %>
<h3><%= @company.name -%>から招待状が届いています</h3>
<h4>ユーザータイプ(#TODO仮文言):<%= C.user_type.disp(@token.user_type) %></h4>
  <p>ユーザー情報を入力してください</p>
  <%= form_for @user, :url => users_invitation_register_path do |f| %>
      <table>
      <tr>
        <td>名前</td>
        <td><%= f.text_field :name, :size => '16', :required => true %></td>
        <td></td>
      </tr>
      <%= f.fields_for :profile_attributes  do |profile| -%>
      <tr>
        <td>部署</td>
        <td><%= profile.text_field :section, :size => '16', :required => true %></td>
        <td>部署名（必須)</td>
      </tr>
      <tr>
        <td>肩書き</td>
        <td><%= profile.text_field :position, :size => '16' %></td>
        <td>肩書きを入力してください</td>
      </tr>
      <tr>
        <td>性別</td>
        <td>
          <%- [["男","1"],["女", "2"]].each  do |opt| -%>
	    <%= opt.first %>
            <%= profile.radio_button :sex, opt.last, :required => true %>
          <%- end -%>
        </td>
        <td>(必須)</td>
      </tr>
      <tr>
        <td>誕生日</td>
        <td><%= profile.date_select :birthday %></td>
        <td></td>
      </tr>
      <%- end -%>
      <tr>
        <td>パスワード</td>
        <td><%= f.password_field :password, :size => '16', :required => true %></td>
        <td>半角英数で6文字以上</td>
      </tr>
      <tr>
        <td>パスワード（確認用）</td>
        <td><%= f.password_field :password_confirmation, :size => '16', :required => true %></td>
        <td>半角英数で6文字以上</td>
      </tr>
    </table>
    <%= hidden_field_tag :code, @token.code %>
    <br />
    <center><%= f.submit '登録' %></center>
  <% end %>
  <br />
  <br />
</div>