config/routes.rb
Rocketstart::Application.routes.draw do

  root :to => "general#index"

  get "/login" => "session#new"
  match 'logout' => 'session#destroy'

  resource :session, :controller => :session, :only => [:create, :destroy]
  resource :remined, :only => [:new, :create, :edit, :update], :controller => 'users/remined'
  resource :entry, :controller => :entry do
    collection { get(:complete) }
  end

  #userに関する関する責務
  resources :users
  namespace :users do
    resource :entry, :controller => :entry, :only => [:new, :create] do
      collection { get(:complete) }
    end

    resource :email, :controller => :email, :only => [:new, :create] do
      collection do 
        get :complete
        get :send_complete
      end
    end
    match "/register/emailchange/:code" => "email#update", :as => "email_change", :via => :put
    match "/register/emailchange/:code" => "email#edit", :as => "email_change"

    #namespace :entry do
    #  resources :search, :only => [:index, :create]
    #end
    resource :register, :only => [:new, :create, :update], :controller => 'register'
    match "/register/remined/:token" => "register#remined", :as => :register_remined_with_token
    match "/register/new/:code" => "register#new", :as => "register_with_token"

    resources :invitation, :only => [:new, :create]
    namespace :invitation do
      resource :register, :only => [:new, :create], :controller => "register" do
        collection { get(:complete) }
      end
      match "register/new/:code" => "register#new", :as => :register_invitation_with_token
    end

  end

  resource :dashboard, :controller => :dashboard, :only => [:show]

end

app/models/user.rb
class User < ActiveRecord::Base
  include Authentication
  EditTargets = []
  RollName = ""
  attr_accessor :password, :password_confirmation, :roll

  validates :email, :uniqueness => true, :presence => true
  validates :name, :presence => true
  validates :password, :length => { :minimum => 6 }, :on => :create
  validates :password, :presence => true, :confirmation => true, :on => :create

  before_save :encrypt_password

  has_many :reports
  has_many :drop_boxes

  has_many :users_schedules, :class_name => 'Relations::UsersSchedule'
  has_one :profile, :class_name => '::User::Profile'

  accepts_nested_attributes_for :profile

  belongs_to :company

  class << self
    def authenticate_email(email, password)
      return nil if email.blank? || password.blank?
      u = find_by_email(email)
      u && u.authenticated?(password) ? u : nil
    end
  end

  def roll_change
    return if self.roll.blank?
    #TODO:あとでAbstractFactoryとvalidation
    type_text = 
    case self.roll.to_i
    when 1
      "User::Administrator"
    when 2
      "User::President"
    when 3
      "User::EdicationalOfficer"
    when 4
      "User::SystemOfficer"
    when 5
      "User::Staff"
    when 6
      "User::AuditOfficer"
    else
      raise UserTypeNotFound
    end
    self.class.update_all("type='#{type_text}'", ["id = ?", self.id])
  end

  def president?
    self.class == ::User::President
  end

  def user_type
    actor = self.class.to_s.split("::").last
    C.user_type.send(actor.to_sym)
  end

  def waiting_workflows
    ::ApprovalWorkflow.where(user_type: self.user_type)
  end
end

app/models/user/administrator.rb
#coding: utf-8
class User::Administrator < User
  ROLL = "管理者".freeze
  RollOptions = [[::User::Administrator::ROLL,1],[::User::EdicationalOfficer::ROLL,3],[::User::SystemOfficer::ROLL,4],[::User::Staff::ROLL,5]].freeze
  EditTargets = [::User::EdicationalOfficer, ::User::SystemOfficer, ::User::Staff].freeze
  has_many :reports, :class_name => "ApprovalForm", :foreign_key => :user_id
end

app/models/user/audit_officer.rb
#coding: utf-8
class User::AuditOfficer < User
  ROLL = "監査責任者".freeze
end

app/models/user/edicational_officer.rb
#coding: utf-8
class User::EdicationalOfficer < User
  ROLL = "教育責任者".freeze
end

app/models/user/president.rb
#coding: utf-8
class User::President < User
  ROLL = "社長".freeze
  RollOptions = [[::User::Administrator::ROLL,1],[::User::Staff::ROLL,5],[::User::AuditOfficer::ROLL,6]].freeze
  EditTargets = [::User::Administrator, ::User::Staff, ::User::AuditOfficer].freeze
end

app/models/user/profile.rb
class User::Profile < ActiveRecord::Base
end

app/models/user/staff.rb
#coding: utf-8
class User::Staff < User
  ROLL = "従業員".freeze
end

app/models/user/system_officer.rb
#coding: utf-8
class User::SystemOfficer < User
  ROLL = "情報システム・リスク責任者".freeze
end

app/controllers/users/email_controller.rb
#coding: utf-8
class Users::EmailController < ApplicationController
  before_filter :token_required, :only => [:edit, :update]

  def edit
    @user = @token.user
  end

  def create
    token = EmailChangeToken.new(user_id: current_user.id, email: params[:email])
    User::transaction do
      if token.save
        DeliverMailer.email_change(token).deliver
        redirect_to send_complete_users_email_path and return
      else
        render "users/edit"
      end
    end
  end

  def update
    @user = @token.user
    u = User.authenticate(@user.email, params[:password])
    if u && @user.id == u.id
      User::transaction do
        @user.email = @token.email
        @user.save!
        @token.destroy
        redirect_to complete_users_email_path and return
      end
    else
      flash[:error] = "パスワードが違います"
      render "edit"
    end
  end

  def complete; end

  def send_complete; end

  private
  def token_required
    @token = ::EmailChangeToken.where(["code like ? ", "%#{params[:code]}%"]).first
  end

end

app/controllers/users/entry_controller.rb
class Users::EntryController < ApplicationController
  def new
    if params[:master_id].present?
      if master = ::Master::OfficialCompany.find_by_id(params[:master_id])
        @company = ::Company.new(
          :name => master.name,
          :address => master.address,
          :code => master.code,
          :expiration_date => master.expiration_date,
          :agency => master.agency,
          :jis_code => master.jis_code
        )
      else
        @company = ::Company.new
      end
    else
      @company = ::Company.new
    end
    @admin = ::User::Administrator.new
  end

  def create
    @company, @admin = [ ::Company.new, ::User::Administrator.new ]

    #TODO:ohat あとできれいに
    if master = ::Master::OfficialCompany.find_by_id(params[:master_id])
      @company = ::Company.new(
        :name => master.name,
        :address => master.address,
        :code => master.code,
        :expiration_date => master.expiration_date,
        :agency => master.agency,
        :jis_code => master.jis_code
      )
    end

    @admin.attributes = params[:company][:user_administrator]
    params[:company].delete(:user_administrator)

    @company.attributes = params[:company]

    ::Company::transaction do 
      if @company.valid? && @admin.valid?
        @company.save! and @company.reload
        @admin.company_id = @company.id
        @admin.save!
        @token = ActivationToken.create(email: @admin.email)
        DeliverMailer.entry(@token).deliver
        redirect_to complete_users_entry_path and return 
      else
        render "new"
      end
    end
  end
end

app/controllers/users/invitation/register_controller.rb
class Users::Invitation::RegisterController < ApplicationController
  class InvitationTokenNotFound < StandardError; end
  class UserTypeNotFound < StandardError; end
  before_filter :token_required, :except => [:complete]

  def new
    @user = user_klass(@token).new(email: @token.email)
    @company = @token.user.company
  end

  def create
    @user = user_klass(@token).new(email: @token.email, company_id: @token.company_id)
    @company = @token.user.company
    key = @user.class.to_s.split("::").last.underscore
    @user.attributes = params["user_#{key}".to_s]
    ActiveRecord::Base.transaction do
      if @user.save
        @user.status = C.regist_status.REGISTED
        @token.destroy
        DeliverMailer.registed(@user).deliver
        self.current_user= @user
        redirect_to complete_users_invitation_register_path and return
      else
        render "new"
      end
    end
  end

  private
  def token_required
    @token = ::InvitationToken.where(["code like ? ", "%#{params[:code]}%"]).first
    raise InvitationTokenNotFound unless @token.present?
  end

  #TODO:ohta
  #あとでアブストラクトファクトリー
  def user_klass(token)
    case token.user_type
    when 2
      ::User::President
    when 3
      ::User::EdicationalOfficer
    when 4
      ::User::SystemOfficer
    when 5
      ::User::Staff
    when 6
      ::User::AuditOfficer
    else
      raise UserTypeNotFound
    end
  end
end

app/controllers/users/invitation_controller.rb
#coding: utf-8
class Users::InvitationController < ApplicationController
  def new
    @invitation = ::InvitationToken.new(user_id: current_user.id)
  end

  def create
    @invitation = ::InvitationToken.new(user_id: current_user.id, company_id: current_user.company.id)
    @invitation.attributes = params[:invitation_token]

    ActiveRecord::Base::transaction do
      if @invitation.save
        flash[:notice] = "invitationしました"
        DeliverMailer.invitation(@invitation).deliver
        redirect_to(users_path) and return
      else
        render("new") and return
      end
    end
  end
end

app/controllers/users/register_controller.rb
#coding: utf-8
class Users::RegisterController < ApplicationController
  class TokenNotFound < StandardError; end
  before_filter :token_required

  rescue_from TokenNotFound do
    render :text => "token not found"
  end

  def new
    @user = ::User::find_by_email @token.email
  end

  def create
    @user = ::User::find_by_email @token.email
    u = User.authenticate(@user.email, params[:user][:password])

    if u
      ActiveRecord::Base::transaction do
        self.current_user= u
        @user.status = C.regist_status.REGISTED
        c = @user.company
        c.status = C.regist_status.REGISTED
        c.save!
        @user.save!
        @token.destroy
        DeliverMailer.registed(@user).deliver
        redirect_to dashboard_path and return
      end
    else
      flash[:error] = "パスワードが違います"
      render "new"
    end
  end

  private
  def token_required
    #@token = ActivationToken.find_by_code(params[:code])
    #TODO;sqlite?
    @token = ActivationToken.where([" code like ? ", "%#{params[:code]}%"]).first
    raise TokenNotFound unless @token.present?
  end

end

app/controllers/users/remined_controller.rb
#coding: utf-8
class Users::ReminedController < ApplicationController

  def new
    @entry = ActivationToken.new
    @entry.remined = 1
    render :new
  end

  def create
    @entry = ActivationToken.new
    @entry.attributes = params[:activation_token]
    @entry.save!
    if @entry.remined?
      user = User.find_by_email @entry.email
      if user
        DeliverMailer.remined(@entry).deliver
      else
        #ここにユーザー登録されていない場合の処理を書く
      end
    else
      DeliverMailer.entry(@entry).deliver
    end
    render :complete
  end

  def edit
    @entry = ActivationToken.find_by_token(params[:token])
    if @entry
      @user = User.find_by_email @entry.email
    else
      raise TokenNotFound
    end
  end

  def update
    @user = User.find_by_email params[:user][:email]
    @user.attributes = params[:user]
    @user.save!
    ActivationToken.find_by_email(u.email).destroy
    self.current_user = @user
    redirect_to dashboard_path
  end

end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  def index
    @users = User.where(company_id: current_user.company_id)
  end

  def edit
    @user = current_user.company.users.find params[:id]
  end

  def update
    @user = current_user.company.users.find params[:id]
    key = "user_" + @user.class.to_s.split("::").last.underscore

    User::transaction do
      if @user.update_attributes(params[key])
        @user.roll_change
        redirect_to users_path
      else
        render "edit"
      end
    end
  end

  def destroy
    #TODO:権限周りやその他、ひもづいている者を全て削除する
    u = User.find(params[:id])
    (::Schedule.where :owner_id => u.id).each do |s|
      s.destroy
    end
    (::UsersSchedule.where :user_id => u.id).each do |us|
      us.destroy
    end
    u.destroy
    redirect_to(users_url, :notice => 'ユーザーを削除しました。') 
  end
end

app/helpers/users/entry/search_helper.rb
module Users::Entry::SearchHelper
end

app/helpers/users/entry_helper.rb
module Users::EntryHelper
end

app/helpers/users/invitation/register_helper.rb
module Users::Invitation::RegisterHelper
end

app/helpers/users/invitation_helper.rb
module Users::InvitationHelper
end

app/helpers/users/register_helper.rb
module Users::RegisterHelper
end

app/views/users/edit.html.erb
<div id="entry">
  <br />
  <!-- #TODO:yokohama バリデーションの実装 -->
  <% if @user.errors.present? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><span class="red"><%= msg %></span></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h2>ユーザー編集</h2>
  <p>ユーザー情報を入力してください</p>
  <%= form_for @user, :url => user_path(@user) do |f| %>
    <table class="input_base">
      <%- if roll_change? && current_user.class::EditTargets.include?(@user.class) -%>
        <tr>
          <td class="title">権限</td>
          <td><%= f.select :roll, formatted_roll_options(current_user.class::RollOptions), :required => true %></td>
          <td></td>
        </tr>
      <%- end -%>
      <tr>
        <td class="title">名前</td>
        <td><div class="required">必須</div></td>
        <td><%= f.text_field :name, :required => true, :class => :text %></td>
        <td></td>
      </tr>
      <%= f.fields_for :profile_attributes, @user.profile  do |profile| -%>
      <tr>
        <td class="title">部署</td>
        <td></td>
        <td><%= profile.text_field :section, :class => :text, :value => @user.profile.section %></td>
      </tr>
      <tr>
        <td class="title">肩書き</td>
        <td></td>
        <td><%= profile.text_field :position, :class => :text, :value => @user.profile.position %></td>
      </tr>
      <tr>
        <td class="title">性別</td>
        <td><div class="required">必須</div></td>
        <td>
          <%- [["男","1"],["女", "2"]].each  do |opt| -%>
	    <%= opt.first %>
            <%= profile.radio_button :sex, opt.last, :required => true %>
          <%- end -%>
        </td>
      </tr>
      <tr>
        <td class="title">誕生日</td>
        <td><div class="required">必須</div></td>
        <td><%= profile.date_select :birthday, :value => @user.profile.birthday %></td>
      </tr>
      <tr>
        <td class="submit" colspan="3">
          <div id="send_button" class="button">
            <input type="submit" value="プロフィールを変更する" />
          </div>
        </td>
      </tr>
    <%- end -%>
  </table>
  <br />
  <br />
  <%- if me?(@user) -%>
    <table class="input_base">
      <tr>
        <td class="title">パスワード</td>
        <td><div class="required">必須</div></td>
        <td><%= f.password_field :password, :class => :text %></td>
        <td>半角英数で6文字以上</td>
      </tr>
      <tr>
        <td class="title">パスワード（確認用）</td>
        <td><div class="required">必須</div></td>
        <td><%= f.password_field :password_confirmation, :class => :text %></td>
        <td>半角英数で6文字以上</td>
      </tr>
      <tr>
        <td class="submit" colspan="4">
          <div id="send_button" class="button">
            <input type="submit" value="パスワードを変更する" />
          </div>
        </td>
      </tr>
    </table>
  <%- end -%>
  <br />
  <br />
  <% end %>
  <%- if me?(@user) -%>
    <%= form_for @user, :url => users_email_path, :method => :post do |f| -%>
      <table class="input_base">
        <tr>
          <td class="title">メールアドレス</td>
          <td><div class="required">必須</div></td>
          <td><%= text_field_tag :email, @user.email, :class => :text, :maxlength => 40, :type => :email, :required => true -%></td>
          <td>有効なメールアドレスを入力してください</td>
        </tr>
        <tr>
          <td class="submit" colspan="4">
            <div id="send_button" class="button">
              <input type="submit" value="メールアドレスを変更する" />
            </div>
          </td>
        </tr>
      </table>
    <% end %>
  <% end %>
<br />
<br />
</div>

app/views/users/index.html.erb
<script type="text/javascript">
<!--

  $(document).ready(function(){
    $("div.navi").append("&nbsp;<a href='/users/invitation/new'>利用者の追加</a>");
    $("div.navi").append("&nbsp;<a href='/users/invitation/new'>利用者の追加</a>");
    $("div.navi").append("&nbsp;<a href='/users/invitation/new'>利用者の追加</a>");
  });

//-->
</script>
    <%#= link_to '利用者の追加', new_users_invitation_path %>

<section>
<h2>利用者一覧</h2>
<table class='base'>
  <thead>
    <tr>
      <th>名前</th>
      <th>E-Mail</th>
      <th>権限</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |u| %>
    <tr>
      <td><%= u.name %></td>
      <td><%= u.email %></td>
      <td><%= u.class::ROLL %></td>
      <td>
        <% if current_user.instance_of? ::User::Administrator %>
          <%= link_to image_tag('s_config.png'), edit_user_path(u) %>
        <% elsif u.id == current_user.id %>
          <%= link_to image_tag('s_config.png'), edit_user_path(u) %>
        <% end %>
      </td>
      <td>
        <% if current_user.instance_of? ::User::Administrator %>
          <% unless u.instance_of? ::User::Administrator %>
            <%= link_to image_tag('s_delete.png'), 
                        user_path(u), 
                        :confirm => '本当に削除してもよろしいですか？', 
                        :method => :delete, 
                        :id => 'remove' %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<% end %>
</section>

app/views/users/new.html.erb
<div id='entry'>
  <br />
  <p>メールアドレスを入力してください。確認メールが届きます。</p>
  <%= form_for @user, :url => entry_path do |f| %>
    <center>
      <table>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email, :size => '30' %></td>
          <td><%= f.submit '送信' %></td>
        </tr>
      </table>
    </center>
  <% end %>
  <br />
  <br />
</div>